version: '3.4'

services:
  confluence:
    image: haxqer/confluence:9.2.1
    container_name: confluence-srv
    environment:
      - TZ=${TZ}
    depends_on:
      - mysql
    volumes:
      - ./data/confluence:/var/confluence
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8.0
    container_name: mysql-confluence
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

  nginx:
    image: nginx:latest
    container_name: nginx-confluence
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - confluence
    networks:
      - network-bridge
    restart: always

networks:
  network-bridge:
    driver: bridge
